language: php
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

## PHP versions we test against
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 5.6
      env: dependencies=lowest
    - php: 7.0
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=lowest
    - php: hhvm
      env: dependencies=lowest
    - php: nightly
      env: dependencies=lowest
    - php: 5.6
      env: dependencies=highest
    - php: 7.0
      env: dependencies=highest
    - php: 7.1
      env: dependencies=highest
    - php: 7.2
      env: dependencies=highest
    - php: hhvm
      env: dependencies=highest
    - php: nightly
      env: dependencies=highest

## Run the appropriate composer command
install:
  - if [ -z "$dependencies" ]; then composer install; fi;
  - composer config --unset platform.php
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - composer show

## Run the actual test
script: make travis

after_script: make travis-coverage
